# Generated by Django 5.0 on 2024-01-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadedfile_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='hashed_file_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
