# Generated by Django 5.0 on 2024-01-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadedfile_hashed_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='hashed_file_id',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='unique_token',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
