# Generated by Django 4.1 on 2024-05-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_useractivity_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='ip_address',
        ),
    ]
